### ISSUE TITLE
Confusion between GitHub and git

### ISSUE THREAD

**Issue by windmark** [andkret/Cookbook#16]
First of all, great work with this really nice document and resource!

I have a small comment in the `Get Familiar With Github` chapter and it's about the confusion between Github and `git` itself. Although Github right now is the biggest hosting service for git, it's very important to make the distinction between git and the service that is Github.

**Comment by andkret** [comment]
This is a very good point! I'll change it to Get Familiar With Git in release 1.2
Thank you very much!
