### ISSUE TITLE
Compilation error on case sensitive filesystems

### ISSUE THREAD

**Issue by php1ic** [andkret/Cookbook#17]
In the main file when including figures, you use "images/", but the directory is actually called "Images". This prevents compilation on ubuntu (and I assume all *nix systems).

```
! LaTeX Error: File `Images/Machine-Learning-Pipeline' not found.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.112 ...twidth]{Images/Machine-Learning-Pipeline}
```

**Comment by andkret** [comment]
I'm not sure how to fix this. I renamed the folder locally, but it's not showing up in my GitHub Desktop.

**Comment by php1ic** [comment]
Strange, unfortunately I have no experience with GitHub Desktop so can't offer any advice for that,

Looks like you need to either rename with git on the command line:
https://stackoverflow.com/questions/11183788/in-a-git-repository-how-to-properly-rename-a-directory

Or it is possible to rename directly on the github page:
https://github.blog/2013-03-15-moving-and-renaming-files-on-github/

**Comment by andkret** [comment]
This issue is solved
