### ISSUE TITLE
Add Graph Databases to Cookbook

### ISSUE THREAD

**Issue by thmoeller** [andkret/Cookbook#31]
Hallo @andkret, appretiate your work here very much. For completeness i would like to see Graph Databases, especially Neo4J. Saw some very cool stuff from
their Graph Connect with Neo4J and Spark. 
By the way, just for improvement, i would suggest to add some descriptive words to the doc, where currently only a podcast link or youtube link is available. Only to avoid the cookbook becoming just a link collection. 
BR Moe

**Comment by andkret** [comment]
@sharad-vm added an introduction.
