### ISSUE TITLE
phishing link in your README.md

### ISSUE THREAD

**Issue by umairsiddiqui-digitek** [andkret/Cookbook#35]
hi,

i was reading project description (README.md) and then i thought about reading your medium publications

```
I have a Medium publication where you can publish your data engineer articles:
[Medium publication](https://link.medium.com/9oi1VDrhPW)

```

this redirect to another URL

https://rsci.app.link/9oi1VDrhPW?_p=f054275bf62ada7e63800b60266d75

**the Avast antivirus trigger a phishing URL detection** I am confused!!!
![Capture_phising](https://user-images.githubusercontent.com/41374313/60667176-4dd12500-9e82-11e9-974c-3efe81fec6f1.PNG)

**Comment by emptymalei** [comment]
hmm, my browser redirects me to the actual medium post.

**Comment by andkret** [comment]
@emptymalei Yeah works for me too. Don't have a problem. Tried it on multiple devices. Leads directly to Medium

**Comment by andkret** [comment]
Could not replicate this since then. 
Closing this issue
