### ISSUE TITLE
Not able to download the PDF version book form Github link

### ISSUE THREAD

**Issue by SrinivasaDK** [andkret/Cookbook#51]
Hi And,

I am not able to download the PDF version book from the link you have mentioned in the Github link. Please advise. Not sure this issue is only for me or others as well. Thanks! 

Regards,
Srini

**Comment by andkret** [comment]
Just tried the download shortcut on the main GitHub page. Works for me. 
Anyone else?

**Comment by andkret** [comment]
You can also click on the PDF directly. On the top right corner of that page is a download button

**Comment by SrinivasaDK** [comment]
Thanks, it is working now.
