### ISSUE TITLE
Interview Questions Link on main page is broken

### ISSUE THREAD

**Issue by jgold189** [andkret/Cookbook#66]
In the README.md the link to the interview questions is https://github.com/andkret/Cookbook/blob/master/InterviewQuesitons.md
which is a misspelling of the actual link to the interview questions which is https://github.com/andkret/Cookbook/blob/master/InterviewQuestions.md
so it appears as if there are no interview questions

**Comment by andkret** [comment]
Fixed it. Thanks 👍
