### ISSUE TITLE
PDF download Link

### ISSUE THREAD

**Issue by VellalaVineethKumar** [andkret/Cookbook#84]
Where is the link to download a PDF version of this cookbook?

**Comment by andkret** [comment]
In the old LaTeX version branch. I no longer update it.

**Comment by VellalaVineethKumar** [comment]
@andkret Where can i find the updated PDF of your Book?

**Comment by andkret** [comment]
Nowhere. I discontinued the pdf updates. This way you always have access to the newest version online, here on GitHub. Otherwise you would need to download the pdf all the time

**Comment by VellalaVineethKumar** [comment]
@andkret  Thanks for your quick response!

**Comment by andkret** [comment]
Any time! Sorry, I know It's not what you were looking for.

**Comment by rasikas** [comment]
Are you planning to continue on the HandsOn section? Last update video was around June last year? thank you (https://github.com/andkret/Cookbook/blob/master/HandsOnCourse.md#switch-processing-from-zeppelin-to-spark)

**Comment by rasikas** [comment]
> Any time! Sorry, I know It's not what you were looking for.

Are you planning to continue on the HandsOn section? Last update video was around June last year? thank you (https://github.com/andkret/Cookbook/blob/master/HandsOnCourse.md#switch-processing-from-zeppelin-to-spark)
